import {v4 as uuid} from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    imgSrc: "https://assetpoint.netlify.app/images/book-1.jpg",
    title: "The Psychology of Money",
    author: "by Morgan Housel",
    oldPrice: 399,
    newPrice: 290,
    discount: 40,
    rating: 4.5,
    isBestSeller: true,
    category: "self-help",
  },
  {
    _id: uuid(),
    imgSrc: "https://assetpoint.netlify.app/images/book-2.png",
    title: "Rich Dad Poor Dad",
    author: "by Robert Kiyosaki",
    oldPrice: 499,
    newPrice: 302,
    discount: 39,
    rating: 4.5,
    isBestSeller: false,
    category: "real-estate",
  },
  {
    _id: uuid(),
    imgSrc: "https://assetpoint.netlify.app/images/book-3.png",
    title: "Let's Talk Money",
    author: "by Monika Halan",
    oldPrice: 399,
    newPrice: 230,
    discount: 42,
    rating: 4.5,
    isBestSeller: false,
    category: "stock-invest",
  },
  {
    _id: uuid(),
    imgSrc: "https://assetpoint.netlify.app/images/book-4.jpg",
    title: "The Intelligent Investor",
    author: "by Benjamin Graham",
    oldPrice: 799,
    newPrice: 480,
    discount: 40,
    rating: 4.5,
    isBestSeller: true,
    category: "stock-invest",
  },
  {
    _id: uuid(),
    imgSrc: "https://assetpoint.netlify.app/images/book-5.png",
    title: "The Richest Man in Babylon",
    author: "by George Clason",
    oldPrice: 150,
    newPrice: 99,
    discount: 34,
    rating: 4,
    isBestSeller: false,
    category: "self-help",
  },
  {
    _id: uuid(),
    imgSrc: "https://assetpoint.netlify.app/images/book-6.png",
    title: "Richer, Wiser, Happier",
    author: "by William Green",
    oldPrice: 599,
    newPrice: 469,
    discount: 22,
    rating: 4.5,
    isBestSeller: false,
    category: "stock-invest",
  },
  {
    _id: uuid(),
    imgSrc: "https://assetpoint.netlify.app/images/book-6.png",
    title:
      "ART OF HANDLING MONEY AND INVESTMENTS: A Practical Guide to Personal Finances",
    author: "by Rajiv K. Tayal",
    oldPrice: 550,
    newPrice: 450,
    discount: 18,
    rating: 5,
    isBestSeller: false,
    category: "self-help",
  },
  {
    _id: uuid(),
    imgSrc: "https://assetpoint.netlify.app/images/book-6.png",
    title: "Rich Dads Cashflow Quadrant: Guide to Financial Freedom",
    author: "by Robert Kiyosaki",
    oldPrice: 550,
    newPrice: 321,
    discount: 42,
    rating: 4,
    isBestSeller: false,
    category: "self-help",
  },
  {
    _id: uuid(),
    imgSrc: "https://assetpoint.netlify.app/images/book-6.png",
    title: "Rich Dads Cashflow Quadrant: Guide to Financial Freedom",
    author: "by Robert Kiyosaki",
    oldPrice: 550,
    newPrice: 321,
    discount: 42,
    rating: 4,
    isBestSeller: false,
    category: "self-help",
  },
];
