const USER_ACTIONS = {
  ADD_TO_WISHLIST: "ADD_TO_WISHLIST",
  REMOVE_FROM_WISHLIST: "REMOVE_FROM_WISHLIST",
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  INCREMENT_PRODUCT: "INCREMENT_PRODUCT",
  DECREMENT_PRODUCT: "DECREMENT_PRODUCT",
};

export {USER_ACTIONS};
